name: bombastic_banking
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  local_auth: ^3.0.0
  local_auth_android: ^2.0.2
  local_auth_darwin: ^2.0.1
  http: ^1.1.0
  provider: ^6.1.5+1
  shared_preferences: ^2.1.1
  flutter_secure_storage: ^8.1.0
  flutter_dotenv: ^6.0.0
  nfc_manager: ^4.1.1
  nfc_manager_ndef: ^1.1.0
  ndef_record: ^1.3.3
  jwt_decode: ^0.3.1
  elevenlabs_agents: ^0.3.0
  permission_handler: ^12.0.1
  get_it: ^9.2.0
  flutter_webrtc: ^1.2.1
  audio_session: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
